
import React from 'react';
import { useCaseContext } from '../context/CaseContext';
import { UserPersona } from '../types';
import { ScanEye, UploadCloud, CheckCircle2, UserPlus, Send, LayoutDashboard, MousePointerClick, BookOpen, Activity, FileText, Check, ShieldCheck, HelpCircle } from 'lucide-react';

interface HelpStepProps {
  id: number;
  icon: React.ElementType;
  title: string;
  description: string;
  colorClass: string;
}

const HelpStep: React.FC<HelpStepProps> = ({ id, icon: Icon, title, description, colorClass }) => (
  <div className="flex items-start bg-white p-6 rounded-2xl border border-slate-200 shadow-sm relative overflow-hidden group hover:shadow-md transition-shadow">
     <div className={`absolute top-0 left-0 w-1.5 h-full ${colorClass}`}></div>
     <div className="mr-5 flex-shrink-0">
        <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${colorClass.replace('bg-', 'bg-opacity-10 text-').replace('text-', 'bg-')}`}>
           <Icon size={20} className="opacity-100" />
        </div>
        <div className="mt-2 text-center text-xs font-bold text-slate-400">STEP {id}</div>
     </div>
     <div>
        <h3 className="text-lg font-bold text-slate-800 mb-2">{title}</h3>
        <p className="text-slate-600 leading-relaxed text-sm">{description}</p>
     </div>
  </div>
);

export const HelpView: React.FC = () => {
  const { currentUser } = useCaseContext();

  const renderContent = () => {
    // PATIENT GUIDE
    if (currentUser === UserPersona.PATIENT) {
        return (
            <div className="space-y-6">
                <HelpStep 
                    id={1}
                    icon={LayoutDashboard}
                    title="Health Dashboard"
                    description="Track your scan status from 'Processing' to 'Ready'. Your dashboard provides real-time updates on your MRI analysis."
                    colorClass="bg-purple-500 text-purple-600"
                />
                <HelpStep 
                    id={2}
                    icon={MousePointerClick}
                    title="Interactive Report"
                    description="Read your summary in plain English. Hover over highlighted medical terms to see instant, easy-to-understand definitions."
                    colorClass="bg-purple-500 text-purple-600"
                />
                <HelpStep 
                    id={3}
                    icon={Activity}
                    title="Action Plan"
                    description="Review the 'Questions to Ask Your Doctor' checklist generated by the AI to prepare for your next visit."
                    colorClass="bg-purple-500 text-purple-600"
                />
                <HelpStep 
                    id={4}
                    icon={BookOpen}
                    title="Education"
                    description="Explore the 'Trusted Resources' links for verified medical research on Endometriosis and related conditions."
                    colorClass="bg-purple-500 text-purple-600"
                />
            </div>
        );
    }

    // PEER REVIEWER GUIDE
    if (currentUser === UserPersona.PEER) {
        return (
            <div className="space-y-6">
                <HelpStep 
                    id={1}
                    icon={LayoutDashboard}
                    title="Task Inbox"
                    description="Check 'Clinical Tools' or your Home Dashboard for cases flagged as 'Pending Review' or 'Action Required'."
                    colorClass="bg-blue-600 text-blue-700"
                />
                <HelpStep 
                    id={2}
                    icon={ShieldCheck}
                    title="Contextual Review"
                    description="View the Primary Radiologist's specific concern (Consultation Note) alongside MIRA's original AI analysis."
                    colorClass="bg-blue-600 text-blue-700"
                />
                <HelpStep 
                    id={3}
                    icon={Check}
                    title="Consensus"
                    description="Enter your assessment in the 'Second Opinion' field to close the loop. Submit the review to return it to the Primary Radiologist."
                    colorClass="bg-blue-600 text-blue-700"
                />
            </div>
        );
    }

    // PRIMARY RADIOLOGIST GUIDE
    return (
        <div className="space-y-6">
            <HelpStep 
                id={1}
                icon={ScanEye}
                title="AI Analysis (MIRA)"
                description="Upload MRI slices. MIRA auto-scans for lesions, validates image quality, and provides initial confidence scores."
                colorClass="bg-teal-600 text-teal-700"
            />
            <HelpStep 
                id={2}
                icon={FileText}
                title="Verification (NORA)"
                description="Review AI findings in the NORA Dashboard. Accept correct detections to build your report or manually edit the finding text."
                colorClass="bg-teal-600 text-teal-700"
            />
            <HelpStep 
                id={3}
                icon={UserPlus}
                title="Peer Consultation"
                description="Use 'Request Peer Review' to route complex cases to a specialist (like Dr. Maryam) with a specific clinical question."
                colorClass="bg-teal-600 text-teal-700"
            />
            <HelpStep 
                id={4}
                icon={Send}
                title="Patient Release"
                description="Finalize the case by clicking 'Approve & Release'. This triggers the LUMA agent to generate the patient-friendly summary."
                colorClass="bg-teal-600 text-teal-700"
            />
        </div>
    );
  };

  const getPersonaColor = () => {
    if (currentUser === UserPersona.PATIENT) return 'text-purple-600 bg-purple-50 border-purple-100';
    if (currentUser === UserPersona.PEER) return 'text-blue-600 bg-blue-50 border-blue-100';
    return 'text-teal-600 bg-teal-50 border-teal-100';
  };

  return (
    <div className="p-8 md:p-12 h-full flex flex-col max-w-5xl mx-auto">
        <header className="mb-10">
            <div className="flex items-center space-x-4 mb-4">
                <div className={`p-3 rounded-xl border ${getPersonaColor()}`}>
                    <HelpCircle size={32} />
                </div>
                <div>
                    <h1 className="text-3xl font-bold text-slate-900">
                        Help & Guide
                    </h1>
                    <p className="text-slate-500">
                        Workflow instructions for <span className="font-semibold">{currentUser}</span>
                    </p>
                </div>
            </div>
        </header>

        <section className="animate-fadeIn">
            {renderContent()}
        </section>
        
        <footer className="mt-12 p-6 bg-slate-100 rounded-2xl border border-slate-200 text-center">
             <p className="text-slate-500 text-sm">
                Need technical support? Contact the IT Helpdesk at <a href="#" className="text-teal-600 font-semibold hover:underline">support@emma-ai.health</a>
             </p>
        </footer>
    </div>
  );
};
